title: feed-view documenatation
decription: Documenation for the feed-view javascripot library 
theme: jekyll-theme-cayman
google_analytics: UA-90014538-4
author: Sem Postma
twitter:
  username: esstudio_site
  card: summary
social:
  name: ESStudio
  links:
    - https://pinterest.com/eestudio0040/
    - https://github.com/LesterGallagher
    - https://twitter.com/esstudio_site
show_downloads: true
